/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as JoinImport } from './routes/join'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated.index'
import { Route as AuthenticatedGroupImport } from './routes/_authenticated.group'
import { Route as AuthenticatedTransactionsImport } from './routes/_authenticated.transactions'
import { Route as AuthenticatedReportImport } from './routes/_authenticated.report'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as never)

const JoinRoute = JoinImport.update({
  path: '/join',
  getParentRoute: () => rootRoute,
} as never)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as never)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as never)

const AuthenticatedGroupRoute = AuthenticatedGroupImport.update({
  path: '/group',
  getParentRoute: () => AuthenticatedRoute,
} as never)

const AuthenticatedTransactionsRoute = AuthenticatedTransactionsImport.update({
  path: '/transactions',
  getParentRoute: () => AuthenticatedRoute,
} as never)

const AuthenticatedReportRoute = AuthenticatedReportImport.update({
  path: '/report',
  getParentRoute: () => AuthenticatedRoute,
} as never)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/group': {
      id: '/_authenticated/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof AuthenticatedGroupImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '': typeof AuthenticatedRoute
  '/': typeof AuthenticatedIndexRoute
  '/group': typeof AuthenticatedGroupRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/report': typeof AuthenticatedReportRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '/': typeof AuthenticatedIndexRoute
  '/group': typeof AuthenticatedGroupRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/report': typeof AuthenticatedReportRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/join': typeof JoinRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/group': typeof AuthenticatedGroupRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/join' | '' | '/' | '/group' | '/transactions' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/join' | '/' | '/group' | '/transactions' | '/report'
  id: '__root__' | '/login' | '/join' | '/_authenticated' | '/_authenticated/' | '/_authenticated/group' | '/_authenticated/transactions' | '/_authenticated/report'
  fileRoutesById: FileRoutesById
}

export interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGroupRoute: typeof AuthenticatedGroupRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
}

const authenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGroupRoute: AuthenticatedGroupRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(authenticatedRouteChildren)

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  JoinRoute: typeof JoinRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  JoinRoute: JoinRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
